name: 'action-lint'
description: 'Action to run the linter'
inputs:
  working-directory:
    description: 'Working directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules: 'recursive'

    - name: Setup
      id: setup
      with:
        node_version: ${{ env.NODE_VERSION }}
        install_command: npm ci --prefer-offline --no-audit
        package_json_dir: ${{ github.workspace }}/${{ inputs.working-directory }}
      uses: drassil/gh-actions-collection/node-setup@master

    - name: Lint check
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
      run: npm run lint:no-fix;
