name: libs pipeline
on:
  workflow_call:
    inputs:
      working-directory:
        description: 'Path where nestjs-yalc is installed'
        required: false
        type: string

  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  PROJECT_ID: libs
  NODE_VERSION: 16
  # other
  GITHUB_TOKEN: ${{ secrets.READ_PACKAGE_TOKEN }}
  NODE_ENV: 'pipeline'
  JWT_SECRET_PVT: 'dummydummy'
  JWT_SECRET_PUB: 'dummydummy'
jobs:
  #===========================
  #
  #  RUN PARALLEL JOBS
  #
  #============================
  linter:
    name: Linter checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: 'recursive'

      - name: Setup
        id: setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          install_command: ci
          package_json_dir: ${{ inputs.working-directory || github.workspace}}
        uses: drassil/gh-actions-collection/node-setup@master

      - name: Lint check
        working-directory: ${{ inputs.working-directory || github.workspace}}
        run: npm run lint:no-fix;

  test-unit-common:
    name: Common libs unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: 'recursive'

      - name: Setup
        id: setup
        with:
          node_version: ${{ env.NODE_VERSION }}
          install_command: ci
          package_json_dir: ${{ inputs.working-directory || github.workspace}}
        uses: drassil/gh-actions-collection/node-setup@master

      - name: Test coverage
        working-directory: ${{ inputs.working-directory || github.workspace}}
        run: |
          npm config set jestworkers=2
          npm run test:cov
