name: GH PR Version bump
on:
  pull_request_target:
    types:
      - labeled
env:
  NODE_VERSION: 20
jobs:
  patch-bump:
    if: github.event.label.name == 'pr-version-patch'
    runs-on: [ubuntu-latest]
    steps:
      - name: Bump version and changelog
        uses: Drassil/action-package-version-bump@main
        with:
          user_name: "drassil-bot"
          user_email: "git-bot@drassil.org"
          ref_branch: "master"
          version_args: "patch"
          node_version: ${{ env.NODE_VERSION }}
  minor-bump:
    if: github.event.label.name == 'pr-version-minor'
    runs-on: [ubuntu-latest]
    steps:
      - name: Bump version and changelog
        uses: Drassil/action-package-version-bump@main
        with:
          user_name: "drassil-bot"
          user_email: "git-bot@drassil.org"
          ref_branch: "master"
          version_args: "minor"
          node_version: ${{ env.NODE_VERSION }}
